# ==========================================================================
# CRE PROJECT SETTINGS FILE
# ==========================================================================
# Global settings shared by all workflows in this project.
# RPC endpoints are required for EVM capabilities (chain reads/writes).

# ==========================================================================
staging-settings:
  rpcs:
    - chain-name: ethereum-testnet-sepolia-base-1
      url: https://sepolia.base.org

# ==========================================================================
production-settings:
  rpcs:
    - chain-name: ethereum-testnet-sepolia-base-1
      url: https://sepolia.base.org
