import { NextRequest, NextResponse } from "next/server";
import { createSupabaseAdminClient } from "@/app/utils/supabase/supabaseAdmin";
import { verifyLinkingToken } from "@/app/utils/linkingToken";

/**
 * Links a Google OAuth user to an existing wallet-based account.
 *
 * SECURITY: Requires a valid linking token generated by /api/auth/initiate-link.
 * The token proves the wallet user initiated the linking flow with their
 * wallet signature, preventing account takeover attacks.
 *
 * Called from AuthProvider after Google OAuth completes successfully.
 */
export async function POST(req: NextRequest) {
  try {
    const body = await req.json();
    const {
      existingUserId,
      googleId,
      googleEmail,
      googleAvatar,
      googleName,
      linkingToken,
    } = body ?? {};

    if (!existingUserId || !googleId) {
      return NextResponse.json(
        { error: "Missing existingUserId or googleId" },
        { status: 400 }
      );
    }

    // SECURITY: Verify the linking token
    if (!linkingToken) {
      return NextResponse.json(
        { error: "Missing linking token. Please initiate linking from the profile page." },
        { status: 401 }
      );
    }

    const tokenPayload = verifyLinkingToken(linkingToken);
    if (!tokenPayload) {
      return NextResponse.json(
        { error: "Invalid or expired linking token. Please try again." },
        { status: 401 }
      );
    }

    // Verify token matches the user being linked
    if (tokenPayload.userId !== existingUserId) {
      console.error("[LINK-GOOGLE] Token userId mismatch:", {
        tokenUserId: tokenPayload.userId,
        requestUserId: existingUserId,
      });
      return NextResponse.json(
        { error: "Linking token does not match user" },
        { status: 403 }
      );
    }

    const admin = createSupabaseAdminClient();

    // Verify the existing user actually exists
    const { data: existing, error: fetchErr } = await admin
      .from("users")
      .select("*")
      .eq("id", existingUserId)
      .single();

    if (fetchErr || !existing) {
      return NextResponse.json(
        { error: "User not found" },
        { status: 404 }
      );
    }

    // Additional security: verify wallet address matches token
    if (existing.wallet_address?.toLowerCase() !== tokenPayload.walletAddress) {
      console.error("[LINK-GOOGLE] Wallet mismatch:", {
        dbWallet: existing.wallet_address,
        tokenWallet: tokenPayload.walletAddress,
      });
      return NextResponse.json(
        { error: "Wallet address mismatch" },
        { status: 403 }
      );
    }

    // Check if Google account is already linked to another user
    const { data: existingGoogleUser } = await admin
      .from("users")
      .select("id")
      .eq("google_id", googleId)
      .neq("id", existingUserId)
      .maybeSingle();

    if (existingGoogleUser) {
      return NextResponse.json(
        { error: "This Google account is already linked to another user" },
        { status: 409 }
      );
    }

    // Update the existing user with Google info, preserving wallet_address
    const { data: updated, error: updateErr } = await admin
      .from("users")
      .update({
        google_id: googleId,
        auth_provider: existing.wallet_address ? "both" : "google",
        avatar: existing.avatar || googleAvatar || null,
        email: existing.email || googleEmail || null,
        name: existing.name || googleName || null,
      })
      .eq("id", existingUserId)
      .select()
      .single();

    if (updateErr) {
      console.error("[LINK-GOOGLE] Update error:", updateErr);
      return NextResponse.json(
        { error: "Failed to link Google account" },
        { status: 500 }
      );
    }

    return NextResponse.json({ success: true, user: updated });
  } catch (err: unknown) {
    console.error("[LINK-GOOGLE] Error:", err);
    return NextResponse.json(
      { error: "Internal server error" },
      { status: 500 }
    );
  }
}
